### ISSUE TITLE
"py3status modules list" and example_module

### ISSUE THREAD

**Issue by frimdo** [ultrabug/py3status#103]
I installed py3status using dnf (fedora) and the "py3status modules" commands are just not working for me.
I belive, that line #124 should be "print(x.example_method([], config))". Am I allowed just to clone py3 status and commit repaired file?

**Comment by ultrabug** [comment]
Hello @frimdo, thanks for reporting this.

I'm not so sure about the faulty line, could you please link to it from here ? And yes, you can also propose a PR by forking the repo :)

Cheers

**Comment by frimdo** [comment]
https://github.com/ultrabug/py3status/blob/master/doc/example_module.py

**Comment by ultrabug** [comment]
You're absolutely right @frimdo, I've fixed it thank you :) does it fix your issue tho ?

**Comment by frimdo** [comment]
I still have problems executing "py3status modules list" in comand line

**Comment by ultrabug** [comment]
Can you show me more ? copy/paste your terminal or something ?

**Comment by frimdo** [comment]
pc@frimdo:~/$ py3status modules list                                                        
usage: py3status [-h] [-c I3STATUS_CONF] [-d] [-i INCLUDE_PATHS] [-n INTERVAL]
                 [-s] [-t CACHE_TIMEOUT] [-v]
py3status: error: unrecognized arguments: modules list
pc@frimdo:~/$

**Comment by ultrabug** [comment]
and your version of py3status ? `py3status -v`

**Comment by frimdo** [comment]
py3status version 2.2 (python 2.7.10)

**Comment by ultrabug** [comment]
Okay then it's simple, this modules listing has been added in py3status v2.4 mate, please upgrade ;)

**Comment by frimdo** [comment]
So there is just 2.2 available in fedora repository. My mistake, I'm sorry. Thanks. :-)

**Comment by ultrabug** [comment]
Then ping your friendly packager ;) or use by pip as you wish ! Cheers mate.
